name: Publish to Maven Central

on:
  push:
    tags:
      - '*.*.*'  # Trigger on version tags like v0.0.1, v1.0.0, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build -Pversion=${{ steps.get_version.outputs.VERSION }}

      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
          echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye

      - name: Publish to Maven Central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          ./gradlew publish \
            -Pversion=${{ steps.get_version.outputs.VERSION }} \
            -Psigning.gnupg.executable=gpg \
            -Psigning.gnupg.passphrase="${GPG_PASSPHRASE}" \
            -Psigning.gnupg.keyName="${GPG_KEY_ID}"
            -PsonatypeUsername="${SONATYPE_USERNAME}"
            -PsonatypePassword="${SONATYPE_PASSWORD}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Release ${{ steps.get_version.outputs.VERSION }}

            Published to Maven Central 🚀

            ### Installation
            ```kotlin
            dependencies {
                implementation("com.datocms:java-datocms:${{ steps.get_version.outputs.VERSION }}")
            }
            ```
          draft: false
          prerelease: false
